NAME: 'Portfolio Rebalance'
MODULE: 'portfolio_rebalance'
CLASS: 'Rebalance'
INTERVAL: '1h'
PERIOD: 300
INCLUDE_BROKER: True
PARAMETERS:
  rebalance_every_N_days: 7
  rebalance_percentages:
    VAS.AX: 40 # %
    VGS.AX: 40 # %
    VGB.AX: 20 # %
  rebalance_pc_tolerance: 5 # % 
  account_leverage: 1
  partial_trade_rounding: 1 # Round trade size to 1 decimal

WATCHLIST: ['VAS.AX',
            'VGS.AX',
            'VGB.AX']